on:
  push:
    branches:
      - master
      - main

jobs:
  repository_versioning:
    runs-on: ubuntu-latest
    name: Repository Versioning via GHVersioniser
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3
        with:
          path: target_repository
          fetch-depth: 0
      - name: Running GHVersioniser
        id: ghversioniser
        uses: luzkan/GHActionsRepo@v1
        with:
          versioniser-username: "GitVersioniser"
          versioniser-email: "luzkan.gitversioniser@github.com"
          routine_version: "last_commit"
          routine_commit: "prefix_tag"
          routine_contribution: "push_main_amend"
          input-argument-1: "Luzkan (from Target Repo)"
      - name: (Test) Output Receiver
        run: echo "The time was ${{ steps.ghversioniser.outputs.time }}"
