on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          path: target_repository
          fetch-depth: 0
      - name: Hello world action step
        id: hello
        uses: luzkan/GHActionsRepo@v1
        with:
          who-to-greet: "Mona the Octocat"
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - run: |
          cd target_repository
          git config user.name RepoVersioniser
          git config user.email repo.versioniser@github.com
          git add .
          git commit -m "Generated via RepoVersioniser (${{ steps.hello.outputs.commit_message }})"
          git push
